apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: w10-deny-unapproved-loadbalancer
spec:
  policyName: w10-deny-unapproved-loadbalancer
  validationActions:
    - Deny
    - Audit
  matchResources:
    namespaceSelector:
      matchLabels:
        platform.aws.accelerator/guardrails: "enabled"
