apiVersion: v1
kind: LimitRange
metadata:
  name: w10-default-container-limits
  namespace: w8-day-2
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 250m
        memory: 256Mi
      max:
        cpu: 500m
        memory: 512Mi
