apiVersion: v1
kind: ResourceQuota
metadata:
  name: w10-cost-guard
  namespace: w8-day-2
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    services.loadbalancers: "1"
