apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w8-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/MinhKhoa2209/minhkhoa-aws-accelerator-p2.git
    targetRevision: HEAD
    path: cloud/w9/lab/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: w8-day-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
