apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: w8-day-2

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - smoke-test-client.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: w8-day-2
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: true
    includeTemplates: true
