apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: announcement-app-runtime
  namespace: w10-secrets-lab
  labels:
    owner: platform-team
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: announcement-app-runtime
    creationPolicy: Owner
    template:
      metadata:
        labels:
          owner: platform-team
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: w10/announcement-app
        property: API_TOKEN
    - secretKey: ROTATION_VERSION
      remoteRef:
        key: w10/announcement-app
        property: ROTATION_VERSION
