apiVersion: v1
kind: Namespace
metadata:
  name: w10-secrets-lab
  labels:
    owner: platform-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: w10-eso-reader
  namespace: w10-secrets-lab
  labels:
    owner: platform-team
