apiVersion: v1
kind: Pod
metadata:
  name: smoke-test-client
spec:
  restartPolicy: Never
  containers:
    - name: client
      image: busybox:1.36
      command: ["sh", "-c", "wget -qO- http://k8s-project-web && sleep 3600"]
