server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /healthz {
        access_log off;
        default_type text/plain;
        try_files /healthz =200;
    }

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}
